title: Zack Grannan's Webpage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zackg.me" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - "index.markdown"
  - "papers.markdown"
  - "personal.markdown"
